### ISSUE TITLE
github 훅

### ISSUE THREAD

**Issue by geusan** [prography/correctcode-back#3]
- 레포 초대 수락되었을 때, pull-request 생성 리뷰어 등록
- 풀리퀘 머지된 경우, 리뷰 완료 처리

**Comment by geusan** [comment]
생각나는 훅 받아야할 것들은 4개

Hook#1 Install GithubApps in Repository
Hook#2 accept invitation of repository(Reviewer action)
Hook#3 push some commits(Reviewee action)
Hook#4 merge branch(Reviewee action or auto merge when the code review is ended)

**Comment by geusan** [comment]
/hooks/github 으로 일괄로 받아서 처리하도록 생성

**Comment by geusan** [comment]
오류 상황을 생각하지 못함

1. 서비스에 가입하지 않은 사용자가 깃헙 앱 인스톨 하는 경우(CodeRepository는 생성하는데, 사용자를 찾을 수 없음 => CodeRepository와 유저는 관계를 깨야할 것 같음)
    1. 로그인 한 후에, 레포 선택
    2. 해당 레포에 깃헙 앱 설치되어 있지 않으면, 설치 요청
    3. 이미 깃헙앱 설치되어 있으면 CodeRepository로 등록
    4. 리뷰 생성
1. 풀리퀘 생성 시기를 정해야함(리뷰이가 요청할 때, 리뷰어가 수락 했을 때) - 시나리오 상으로는 리뷰어가 수락한 후에 풀리퀘가 생성되어야 하는 걸까?
2. 코드리뷰 받고 싶은 브랜치로 이미 풀리퀘(오픈 상태)가 생성된 경우 에러 발생
3. 풀리퀘에 엄한 사람이 참가하는 경우(누군가는 꼭 장난식으로 참여할 수 있음)
3. ~브랜치가 base 보다 뒤에 있는 경우 에러 발생(커밋 위치 비교하는 코드로 해결)~

**Comment by Godsenal** [comment]
1번은 전부 깃헙에서 하는 행동들 아니여?

**Comment by Godsenal** [comment]
앱 설치할 레포선택 전부 깃헙에서 하는거같은데.
